### ISSUE TITLE
unable to install module using  "npm i ngx-img-cropper --save"

### ISSUE THREAD

**Issue by LokiKartik** [web-dave/ngx-img-cropper#1]
Hi.. I am using angular version 5.2.0. I followed the steps you mentioned in documentation. But I am unable to import the module
' "import { ImageCropperComponent, CropperSettings } from "ngx-img-cropper"  '. I am getting module not found error.

**Comment by FunClub** [comment]
me too

**Comment by FunClub** [comment]
the same error

**Comment by web-dave** [comment]
OK, I'll check. you're at 0.9.2

**Comment by web-dave** [comment]
UH, damn, my fault. sorry, now it works. 0.9.3 is fixed

**Comment by web-dave** [comment]
double checked it. fixed. 😅
