### ISSUE TITLE
Testing a component that uses the image cropper within its template

### ISSUE THREAD

**Issue by andyalam** [web-dave/ngx-img-cropper#12]
Is there any way to get this to work with tests? I'm not sure if it's my setup that's causing failure but whenever I test a component with the image cropper within it's template I receive this error:

`Failed: Template parse errors:
	Can't bind to 'image' since it isn't a known property of 'img-cropper'.`

This is with importing ImageCropperModule into my testing module.

**Comment by Never7Dice** [comment]
Can you share the way you solved the issue, please?
