### ISSUE TITLE
template async data.image

### ISSUE THREAD

**Issue by nphias** [web-dave/ngx-img-cropper#155]
I have a modal for selecting an image background.. 
The user selects the image and the preview never loads because **data.image** is not asynched (observable or promise)
(I have to close and reopen the modal to see the preview )

```
<span class="result rounded" *ngIf="data.image">
  <img
    [src]="data.image"
    [width]="cropperSettings.croppedWidth"
    [height]="cropperSettings.croppedHeight"
  />
</span>
```

one should be able to do:

```
<span class="result rounded" *ngIf="data.image | async">
  <img
    [src]="data.image"
    [width]="cropperSettings.croppedWidth"
    [height]="cropperSettings.croppedHeight"
  />
</span>
```

but it requires making an asynchable image reference in the code

**Comment by web-dave** [comment]
data.image seemse to be a Observable. so you need to subscribe in some way.

Should work like this:
```ts
<span class="result rounded" *ngIf="(data.image | async) as image">
  <img
    [src]="image"
    [width]="cropperSettings.croppedWidth"
    [height]="cropperSettings.croppedHeight"
  />
</span>
```
