### ISSUE TITLE
Allow scroll over image on mobile

### ISSUE THREAD

**Issue by victorivens05** [web-dave/ngx-img-cropper#16]
Hello, I'm using the img-cropper successfully in an Ionic App.

The problem is that the image, when selected, occupy basically all the screen at once, and the users need to scroll in order to send the form. They're not being able to scroll though, because the scroll on top of the image is prevented, and there isn't elsewhere to scroll.

~~I looked in the code, and it would be a simple check if the Touch started on top of any of the five handlers and only `preventDefault` (and keep doing anything else), if the touch started on any handler. Sadly, I couldn't figure out how to check if the touch is over any handler, so I couldn't send a PR.~~

~~Hate to show up with problems without solutions, but this should be simple.~~

I sent a PR https://github.com/web-dave/ngx-img-cropper/pull/19 with a solution. It apparently solve the problem.

Thanks

**Comment by web-dave** [comment]
PR merged and published. thx mate
