### ISSUE TITLE
Error while doing a ng build --prod

### ISSUE THREAD

**Issue by emilioblazquez** [web-dave/ngx-img-cropper#3]
Hi there.
After migrating my app from Angular 4 to Angular 5 I faced the following error while doing a ng build --prod in order to deploy it to my production server:
```bash
ERROR in : Unexpected value 'ImageCropperModule in repo/almagro-client/node_modules/ngx-img-cropper/src/imageCropperModule.d.ts' imported by the module 'SharedModule in repo/alma
gro-client/src/app/resources/shared.module.ts'. Please add a @NgModule annotation.
```
Could it be something I'm doing wrong? Here's the output of my ng -v command in case it might help:
                

> Angular CLI: 1.6.7
> Node: 8.9.0
> OS: win32 x64
> Angular: 5.2.3
> ... animations, common, compiler, compiler-cli, core, forms
> ... http, language-service, platform-browser
> ... platform-browser-dynamic, router
> 
> @angular/cli: 1.6.7
> @angular-devkit/build-optimizer: 0.0.42
> @angular-devkit/core: 0.0.29
> @angular-devkit/schematics: 0.0.52
> @ngtools/json-schema: 1.1.0
> @ngtools/webpack: 1.9.7
> @schematics/angular: 0.1.17
> typescript: 2.5.3
> webpack: 3.10.0

**Comment by web-dave** [comment]
please try again. v0.9.7 should be fixed.
(had problems to publish)

**Comment by emilioblazquez** [comment]
Thank you so much for your awesome work! :)
I'll try as soon as I can and I will let you know if I have any problem.
