### ISSUE TITLE
Blank Canvas in Safari and Firefox

### ISSUE THREAD

**Issue by MatthewLHolden** [web-dave/ngx-img-cropper#38]
I'm performing a few operations before loading the cropper.

1. Detect a file
2. Detect orientation
3. Convert to base64
4. Fix orientation
5. Use the fixed orientation base64 as the image src
6. This works on chrome and the canvas displays the correct image

However on Safari and firefox, an empty canvas is displayed. The correct settings for height and width have been adhered to. However, 'this.data' does not seem to get populated. Any help here would be greatly appreciated...

    `getBase64(file, orientation) {

       var reader = new FileReader();
       reader.readAsDataURL(file);
       reader.onload = () => {

         var base64 = reader.result;
         this.resetOrientation(base64, orientation, (resetBase64Image) => {
        
           if (mySettingIsEnabled) {        
             var image: any = new Image();    
             var that = this;
             image.src = resetBase64Image;      
             that.cropper.setImage(image);
           } else {
             // Call another function
           }
         });
       };
       reader.onerror = (error) => {
         console.log('Error: ', error);
       };
      }`

(I'm aware cropper has some exif functionality, but I only use cropper when a certain setting is enabled, therefore I had to code my own orientation fixing when that option is disable on my end. As a result, I put all images through my code/process)

**Comment by MatthewLHolden** [comment]
I think I might be able to find a way around this. I'll post back if I do. :)

**Comment by lblower** [comment]
Any Update @MatthewLHolden  did you found a work around.

**Comment by MatthewLHolden** [comment]
Hi @lblower - I wrote a blog to remind myself of my findings. Hopefully it may help you: 

[](https://matthewholdendev.wordpress.com/2018/06/02/angular-firebase-correcting-image-exif-orientation-before-upload/)
