### ISSUE TITLE
When is Angular 6 supported

### ISSUE THREAD

**Issue by Anberm** [web-dave/ngx-img-cropper#39]
Angular 6 supported,please!

**Comment by ultrakill93** [comment]
Yes please make this happen

**Comment by Jamilammar** [comment]
That would be so great if you did that.

**Comment by vanschroeder** [comment]
please do make this happen. Presently having to ditch this module and find an alternative solution, as a rollback to angular 5 is not possible

**Comment by cburger** [comment]
I am getting the following warning from NPM:

`ngx-img-cropper@0.10.4 requires a peer of @angular/common@^5.0.0 but none is installed. You must install peer dependencies yourself.`

Everything works fine with Angular 6, the package dependencies just need to be updated to silence the warnings.

**Comment by guillaume-ro-fr** [comment]
Related to #32

**Comment by web-dave** [comment]
We are fully compatible to angular 8. Ivy support not tested yet.
