### ISSUE TITLE
How to control the size and proportion of the crop area

### ISSUE THREAD

**Issue by templth** [web-dave/ngx-img-cropper#46]
Hello,

I try to control the size and proportion of the crop area. I want it to be a square or a rectangle but with a ratio between width and height. I tried to use the properties `height`, `width`, `croppedHeight` and `croppedWidth` but without success at the level of the configuration.

Could you give some hints about the way to implement this approach?
Thanks!

**Comment by web-dave** [comment]
Please find the showcase here:
https://github.com/web-dave/ngx-blog/tree/master/src/app/cropper
(https://webdave.de/ngx-img-cropper)

**Comment by faelpinho** [comment]
@templth Hello. Have you already found a viable way to control the size and proportion?
Which version are you using? I'm using v 9.0.0.
