### ISSUE TITLE
Image cropper is not working with PNG image format

### ISSUE THREAD

**Issue by rajwcg** [web-dave/ngx-img-cropper#50]
I am uploading a png image and cropper is displaying images but cropping feature is not working. When I save this image to server in jpg format and reloading its again. Its started working.
For JPG images its working finr from start of uploading images

Can someone help me to fix issue with PNG images?

**Comment by web-dave** [comment]
sorry for this delayed response.
It should work. a showcase can be found here: https://webdave.de/ngx-img-cropper
