### ISSUE TITLE
Cannot read property 'setImage' of undefined

### ISSUE THREAD

**Issue by CharlesGC** [web-dave/ngx-img-cropper#51]
I want to use a custom input in ng-img-cropper, but when I write in the demo style, it will prompt me "ERROR TypeError: Cannot read property 'setImage' of undefined", my angular version is 5.2.11, please help me, thank you very much.
![image](https://user-images.githubusercontent.com/18606255/44903047-1a8fa800-ad3e-11e8-9e0a-1bc444a4e20f.png)
![image](https://user-images.githubusercontent.com/18606255/44903064-24191000-ad3e-11e8-9a90-a075cedee186.png)
![image](https://user-images.githubusercontent.com/18606255/44903095-34c98600-ad3e-11e8-8f27-8bbb0295392d.png)

**Comment by SafnaAzeez** [comment]
Initialize cropper with
@ViewChild(ImageCropperComponent) cropper:ImageCropperComponent;

instead of

@ViewChild('cropper', undefined) cropper:ImageCropperComponent;

it worked for me.

**Comment by Sathishchary** [comment]
@SafnaAzeez  thanks, it's working for me.
