### ISSUE TITLE
Capture in portrait mode converted to landscape mode. Why ?

### ISSUE THREAD

**Issue by Camille-D** [web-dave/ngx-img-cropper#52]
Hello everyone,

I have a problem with IOS. When I take a picture in portrait mode with the camera it is saved in landscape mode. Is there anything more to do to make it work? This problem only appears in the context of a photo capture.

Thank you for your help ^^

**Comment by lizjulien** [comment]
It's because of exif problem with mobile capture and orientation at redraw. See https://medium.com/wassa/handle-image-rotation-on-mobile-266b7bd5a1e6
I'm going to try to purpose a fix for that.
