### ISSUE TITLE
while doing ng build --prod on Angular 6.1.3

### ISSUE THREAD

**Issue by zhangjinsong** [web-dave/ngx-img-cropper#59]
On running ng build --prod, I'm getting below error :
 ERROR in : Type ImageCropperComponent in D:/gs-unifiedPortal/node_modules/ngx-img-cropper/src/imageCropperComponent.d.ts is part of the declarations of 2 modules: ImageCropperModule in D:/gs-unifiedPortal/node_modules/ngx-img-cropper/src/imageCropperModule.d.ts and UserCetnerModule in D:/gs-unifiedPortal/src/app/user-center/user-center.module.ts! Please consider moving ImageCropperComponent in D:/gs-unifiedPortal/node_modules/ngx-img-cropper/src/imageCropperComponent.d.ts to a higher module that imports ImageCropperModule in D:/gs-unifiedPortal/node_modules/ngx-img-cropper/src/imageCropperModule.d.ts and UserCetnerModule in D:/gs-unifiedPortal/src/app/user-center/user-center.module.ts. You can also create a new NgModule that exports and includes ImageCropperComponent in D:/gs-unifiedPortal/node_modules/ngx-img-cropper/src/imageCropperComponent.d.ts then import that NgModule in ImageCropperModule in D:/gs-unifiedPortal/node_modules/ngx-img-cropper/src/imageCropperModule.d.ts and UserCetnerModule in D:/gs-unifiedPortal/src/app/user-center/user-center.module.ts.

there is my package.json:
![image](https://user-images.githubusercontent.com/12949599/47021105-5f0bc180-d18d-11e8-9900-65463ca36b5e.png)
![image](https://user-images.githubusercontent.com/12949599/47021140-70ed6480-d18d-11e8-90b5-286a741bdff0.png)

How can I solve this problem

**Comment by web-dave** [comment]
now its fully angular CLI compatible and Angular V7 compatible
