### ISSUE TITLE
output Image can become circle image?

### ISSUE THREAD

**Issue by nieshiming** [web-dave/ngx-img-cropper#64]
i find docs has't about this features, if support output circle Image, please tell me ,thanks

**Comment by sr9yar** [comment]
I'm sorry, but that's on the front page:

> rounded:boolean (default: false) - if true, the cropper will be a circle.

Use it like this:
```
    this.cropperSettings = new CropperSettings({
      rounded: true
    });
```

**Comment by nieshiming** [comment]
232323

**Comment by nieshiming** [comment]
#64 222

**Comment by nieshiming** [comment]
> I'm sorry, but that's on the front page:
> 
> > rounded:boolean (default: false) - if true, the cropper will be a circle.
> 
> Use it like this:
> 
> ```
>     this.cropperSettings = new CropperSettings({
>       rounded: true
>     });
> ```

I know, thanks

**Comment by ozzpy** [comment]
I do this, but the result image is not a circle still a square
