### ISSUE TITLE
multiple img-cropper

### ISSUE THREAD

**Issue by potharam** [web-dave/ngx-img-cropper#73]

**Comment by potharam** [comment]
<img-cropper   #Bcropper   [image]="BCropData" [settings]="BcropperSettings" style="text-align: center;display: block; margin-left: auto; margin-right: auto;"></img-cropper>
                         
                          <img-cropper   #Tcropper   [image]="TCropData" [settings]="TcropperSettings" style="text-align: center;display: block; margin-left: auto; margin-right: auto;"></img-cropper>

**Comment by web-dave** [comment]
Don't get the problem.
