### ISSUE TITLE
[Defect] Bounds is not exported

### ISSUE THREAD

**Issue by zijianhuang** [web-dave/ngx-img-cropper#75]
Bounds should be exported.

onCrop() need to use class Bounds. Currently Bounds is not exported, so I have to hack public_api.d.ts a little and add:
`export * from './lib/image-cropper/model/bounds';`

Then things work well.

**Comment by web-dave** [comment]
Oh, thx. I'll have a look.

**Comment by web-dave** [comment]
I've fixed it. thx for your support.
it' available in version 8.0.1
