### ISSUE TITLE
IE edge unable to crop the image using ngx image cropper

### ISSUE THREAD

**Issue by santhoshraju621** [web-dave/ngx-img-cropper#78]
Hi

 This is the error i am getting while i am using the cropper in IE edge.

> ERROR Error: Uncaught (in promise): TypeError: Object doesn't support property or method 'toBlob' TypeError: Object doesn't support property or method 'toBlob' at Anonymous function (http://localhost:4200/vendor.js:205220:13) at ZoneAwarePromise (http://localhost:4200/polyfills.js:8448:17) at ImageCropperComponent.prototype.getCanvasBlob (http://localhost:4200/vendor.js:205219:9) at ImageCropperComponent.prototype.cropToFile (http://localhost:4200/vendor.js:205201:9) at ImageCropperComponent.prototype.cropToOutputType (http://localhost:4200/vendor.js:205165:17) at ImageCropperComponent.prototype.crop (http://localhost:4200/vendor.js:205118:17) at ImageCropperComponent.prototype.doAutoCrop (http://localhost:4200/vendor.js:205074:13) at ImageCropperComponent.prototype.resetCropperPosition (http://localhost:4200/vendor.js:204792:9) at ImageCropperComponent.prototype.checkImageMaxSizeRecursively (http://localhost:4200/vendor.js:204672:13) at Anonymous function (http://localhost:4200/vendor.js:204655:38)

please help to resolve the issue.

**Comment by santhoshraju621** [comment]
if (!HTMLCanvasElement.prototype.toBlob) {
  Object.defineProperty(HTMLCanvasElement.prototype, 'toBlob', {
    value: function (callback, type, quality) {
      var dataURL = this.toDataURL(type, quality).split(',')[1];
      setTimeout(function() {

        var binStr = atob( dataURL ),
            len = binStr.length,
            arr = new Uint8Array(len);

        for (var i = 0; i < len; i++ ) {
          arr[i] = binStr.charCodeAt(i);
        }

        callback( new Blob( [arr], {type: type || 'image/png'} ) );

      });
    }
  });
}


this one resolved the issue

**Comment by ovitrif** [comment]
@santhoshraju621 

I'll fix your comment for better copy-pasta usage and code preview:

```
if (!HTMLCanvasElement.prototype.toBlob) {
Object.defineProperty(HTMLCanvasElement.prototype, 'toBlob', {
value: function (callback, type, quality) {
var dataURL = this.toDataURL(type, quality).split(',')[1];
setTimeout(function() {

    var binStr = atob( dataURL ),
        len = binStr.length,
        arr = new Uint8Array(len);

    for (var i = 0; i < len; i++ ) {
      arr[i] = binStr.charCodeAt(i);
    }

    callback( new Blob( [arr], {type: type || 'image/png'} ) );

  });
}
});
}
```
